### ISSUE TITLE
TypeError with string options converted to integers in Fog OpenStack Storage

### ISSUE THREAD

**Issue by beyhan** [fog/fog-core#210] opened 2017-05-09 15:09 UTC
The method `coerce_options` in [service.rb](https://github.com/fog/fog-core/blob/66779f501906816088dd9b206b6038b6a7f99769/lib/fog/core/service.rb#L161) converts string options containing numbers only into integer values.
This causes a problem together with OpenStack Storage Object when using a `openstack_temp_url_key` which contains only numbers.

When generating a temp [url](https://github.com/fog/fog-openstack/blob/54560edf10e20d67cf08c32408a21a3d1b602167/lib/fog/storage/openstack/models/file.rb#L92) we get the following exception:
```
# --- Caused by: ---
     # TypeError:
     #   no implicit conversion of Integer into String
     #   /Users/cpi/.rvm/gems/ruby-2.4.0/gems/fog-core-1.43.0/lib/fog/core/hmac.rb:22:in `digest'
```

**Comment by plribeiro3000** [comment] 2017-05-09 15:47
Could you provide the input and expected output to better understand your issue?

**Comment by beyhan** [comment] 2017-05-10 07:52
The input `openstack_temp_url_key` is converted to an integer in the `coerce_options` method. This causes the `TypeError` in the `HMAC` class. Here is our code sample (to try the sample the temp URL key has to be set in OpenStack):

```ruby
storage = Fog::Storage::OpenStack.new({
    openstack_temp_url_key: "123456789",
    other_options...})
directory  =  storage.directories.create({
    key: 'some-dir',
    public: false
})
file = directory.files.create({
    key: 'some-file',
    body: 'Hello World',
    content_type: 'text/plain',
    public: false
})

file.url(Time.now.utc + 360000)
#-> TypeError
```

**Comment by icco** [comment] 2017-05-12 17:27
The issue is with this line: https://github.com/fog/fog-core/blob/f6ef6c3d9458bc235be57100acdced264e85e52a/lib/fog/core/service.rb#L166

**Comment by geemus** [comment] 2017-05-15 15:22
I think it originates from wanting to have typed values pulled out of the yaml `~/.fog` type files, probably for port numbers in particular. It's likely that we just never had an occasion such as this come up before. We could try removing it, but I suspect that some things may now expect it to be this way (which means stuff would break). A narrower change might be to try and only apply the conversion when data comes from yaml, but again I am not confident it wouldn't break some things.

So, even if the coercion seems weird it also is dangerous to change. As we haven't really had other concrete issues around it and the scope of this error is pretty narrow, I would suggest the best solution may be to simply change the openstack temp url creation to use to_s on the key before it uses it.

Thoughts?

**Comment by Kiemes** [comment] 2017-05-18 15:10
@geemus fog-openstack library could ensure that it is a string here https://github.com/fog/fog-openstack/blob/4217d76368aa0c570b268e96a3cf21f760ccc967/lib/fog/storage/openstack/requests/get_object_https_url.rb#L56
```
hmac = Fog::HMAC.new('sha1', @openstack_temp_url_key.to_s)
```

wdyt?

**Comment by geemus** [comment] 2017-05-18 15:22
Sounds reasonable to me. Could you PR it for us? (and probably close this before we forget) Thanks!

**Closed** 2017-08-28 22:25 UTC
