### ISSUE TITLE
Unable to perform Fog::Mock.reset

### ISSUE THREAD

**Issue by seanhandley** [fog/fog-core#178] opened 2016-03-18 12:09 UTC
Originally raised over on https://github.com/fog/fog-openstack/issues/59 but the line raising the exception is coming from `Fog::Core`.

```
      uninitialized constant Fog::OpenStack::Compute
Did you mean?  Fog::OpenStack::Compute
               Fog::Compute (NameError)
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.36.0/lib/fog/core/mock.rb:98:in `const_get'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.36.0/lib/fog/core/mock.rb:98:in `block (2 levels) in reset'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.36.0/lib/fog/core/mock.rb:96:in `map'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.36.0/lib/fog/core/mock.rb:96:in `block in reset'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.36.0/lib/fog/core/mock.rb:93:in `map'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.36.0/lib/fog/core/mock.rb:93:in `reset'
        /Users/sean/src/fog-openstack/tests/openstack/bug_mock_reset_tests.rb:14:in `block (3 levels) in <top (required)>'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:140:in `instance_eval'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:140:in `assert'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:116:in `test'
        /Users/sean/src/fog-openstack/tests/openstack/bug_mock_reset_tests.rb:4:in `block (2 levels) in <top (required)>'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /Users/sean/src/fog-openstack/tests/openstack/bug_mock_reset_tests.rb:3:in `block in <top (required)>'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
        /Users/sean/src/fog-openstack/tests/openstack/bug_mock_reset_tests.rb:1:in `<top (required)>'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
        /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'

  1 failed, 0 succeeded in 0.155301 seconds
```

You can reproduce the exception using the following:

``` ruby
Shindo.tests('OpenStack | BugMockReset', ['openstack']) do

  tests("bug mock reset") do
    test("#try_to_reset") do
      Fog.mock!
      p Fog.constants
      Fog::Mock.reset # raises NameError
      true
    end
  end
end
```

**Comment by seanhandley** [comment] 2016-03-18 12:13
This code produces this output.

```ruby
Shindo.tests('OpenStack | BugMockReset', ['openstack']) do

  tests("bug mock reset") do
    test("#try_to_reset") do
      Fog.mock!
      Fog.constants.map do |x|
        next if Fog.autoload?(x)
        x_const = Fog.const_get(x)
        x_const.respond_to?(:constants) && x_const.constants.map do |y|
          next if x_const.autoload?(y)
          p "#{x_const}::#{y}"
        end
      end
      Fog::Mock.reset
      true
    end
  end
end
```
=>
```
"Fog::Openstack::Planning"
"Fog::Core::VERSION"
"Fog::Core::DeprecatedConnectionAccessors"
"Fog::Core::Connection"
"Fog::Core::Utils"
"Fog::Attributes::ClassMethods"
"Fog::Attributes::InstanceMethods"
"Fog::Attributes::Default"
"Fog::Attributes::Array"
"Fog::Attributes::Boolean"
"Fog::Attributes::Float"
"Fog::Attributes::Integer"
"Fog::Attributes::String"
"Fog::Attributes::Time"
"Fog::Attributes::Timestamp"
"Fog::Associations::Default"
"Fog::Associations::ManyIdentities"
"Fog::Associations::ManyModels"
"Fog::Associations::OneModel"
"Fog::Associations::OneIdentity"
"Fog::CurrentMachine::AMAZON_AWS_CHECK_IP"
"Fog::Errors::Error"
"Fog::Errors::MockNotImplemented"
"Fog::Errors::NotFound"
"Fog::Errors::LoadError"
"Fog::Errors::TimeoutError"
"Fog::Errors::NotImplemented"
"Fog::Service::Error"
"Fog::Service::NotFound"
"Fog::Service::NoLeakInspector"
"Fog::Service::Collections"
"Fog::SSH::Mock"
"Fog::SSH::Real"
"Fog::SSH::Result"
"Fog::SCP::Mock"
"Fog::SCP::Real"
"Fog::Time::DAYS"
"Fog::Time::MONTHS"
"Fog::Time::RFC2822_DAY_NAME"
"Fog::Time::RFC2822_MONTH_NAME"
"Fog::Baremetal::OpenStack"
"Fog::Compute::OpenStack"
"Fog::Identity::OpenStack"
"Fog::Image::OpenStack"
"Fog::Metering::OpenStack"
"Fog::Network::OpenStack"
"Fog::Orchestration::OpenStack"
"Fog::Storage::OpenStack"
"Fog::Volume::OpenStack"
"Fog::Formatador::PARSE_REGEX"
"Fog::Formatador::STYLES"
"Fog::Formatador::INDENT_REGEX"
"Fog::Json::VERSION"
"Fog::JSON::EncodeError"
"Fog::JSON::DecodeError"
"Fog::OpenStack::Core"
"Fog::OpenStack::Common"
"Fog::OpenStack::Errors"
"Fog::OpenStack::Compute"
"Fog::OpenStack::IdentityV2"
"Fog::OpenStack::IdentityV3"
"Fog::OpenStack::Image"
"Fog::OpenStack::ImageV2"
"Fog::OpenStack::Metering"
"Fog::OpenStack::Network"
"Fog::OpenStack::Orchestration"
"Fog::OpenStack::Volume"
"Fog::OpenStack::Baremetal"
"Fog::Schema::DataValidator"
"Fog::Nullable::Boolean"
"Fog::Nullable::Integer"
"Fog::Nullable::String"
"Fog::Nullable::Time"
"Fog::Nullable::Float"
"Fog::Nullable::Hash"
"Fog::Nullable::Array"
```

**Comment by geemus** [comment] 2016-03-18 14:24
I imagine this has to do with the extraction and the relative timing of when things are required (or not). But I'm not super sure.

@nirvdrum any insights, looks like you setup the autoload checking stuff here. Thanks!

**Comment by nirvdrum** [comment] 2016-03-18 15:35
I'll try to reproduce. In theory, I only changed things to not autoload constants that haven't already been loaded. Hopefully no one was relying on `Fog::Mock.reset` to load a constant they weren't already using.

**Comment by geemus** [comment] 2016-03-18 16:34
@nirvdrum Thanks for taking a look, I tried to review it, but it made my brain a little melty. Do let me know if there is anything I can help with.

@seanhandley that maybe worth taking a look at. The order in which you address stuff might be problematic?

**Comment by plribeiro3000** [comment] 2016-03-18 17:34
So this is not a `fog-core` issue. If you take a look at the main file at `fog-openstack` [here](https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack.rb#L36) you will see it defines a constant called `Fog::OpenStack::Compute` that should be found at the file `fog/openstack/compute` [here](https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/compute.rb).

But if you take a look it defines another constant instead (`Fog::Compute::OpenStack`). See [here](https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/compute.rb#L3-L5),

**Comment by geemus** [comment] 2016-03-18 18:07
Good catch, thanks!

**Comment by nirvdrum** [comment] 2016-03-18 20:14
Yay! It sounds like I'm off the hook :-)

**Comment by plribeiro3000** [comment] 2016-03-18 20:16
I would suggest to check this kind of problem in the other constant definitions. If you want i can send a PR to `fog-openstack` to fix this and other possible cases. =)

**Comment by seanhandley** [comment] 2016-03-18 20:30
Nice one @plribeiro3000.

I'm confused how this ended up this way. Since I started working on the Fog gem I thought all the individual implementations were of the form `Fog::Compute::PROVIDER` etc.

Not sure I see how to fix it either, without restructuring the whole gem. Or maybe by removing `autoload` and using explicit requirements.

**Comment by plribeiro3000** [comment] 2016-03-18 20:34
Don't worry @seanhandley . I will fix it. Did it for all the other extracted providers. =)

You just need to change

```ruby
module Fog
  module OpenStack
    extend Fog::Provider

    .
    .
    .
    autoload :Compute, File.expand_path('../openstack/compute', __FILE__)
```

to

```
module Fog
  module Compute
    autoload :OpenStack, File.expand_path('../openstack/compute', __FILE__)
  end

  module OpenStack
    extend Fog::Provider
```

**Comment by seanhandley** [comment] 2016-03-18 20:36
Aha. We have a PR to this effect @plribeiro3000 https://github.com/fog/fog-openstack/pull/65

Would you mind a look through it? It seems sane enough to me.

**Comment by plribeiro3000** [comment] 2016-03-18 20:51
Sure. =)

**Comment by geemus** [comment] 2018-07-30 16:50
Marked issue was merged.

**Closed by geemus** 2018-07-30 16:50 UTC
Labels: wontfix
